### ISSUE TITLE
Issue with testing example for kinoml and experiments-binding-affinity

### ISSUE THREAD

**Issue by sukritsingh** [openkinome/experiments-binding-affinity#5]
As requested by @jaimergp - Running an example notebook on kinoml (as dictated by [his presented slides](https://docs.google.com/presentation/d/1jVBlZBlczQYDBcWt8Q266RISLf-aViIUrvHFZlRltek/edit#slide=id.gcedb739bd3_0_113)) resulted in the Papermill errors on both MacOS and Linux systems: 

In both cases the command run was: 
` python run_notebook.py features/featurize-template.ipynb features/example-ligand-only-chembl28-morgan512-1k-subsample.py --overwrite`

Error stack trace for **MacOS**:
```
(experiments-binding-affinity) 31 sukrit@pillarofautumn:~/work/postdoc/kinoml-tutorial/experiments-binding-affinity$ python run_notebook.py \
> features/featurize-template.ipynb \
> features/example-ligand-only-chembl28-morgan512-1k-subsample.py \
> 
Executing:  45%|████████████████████████▏                             | 13/29 [00:07<00:09,  1.63cell/s]
Traceback (most recent call last):
  File "run_notebook.py", line 51, in <module>
    main()
  File "run_notebook.py", line 47, in main
    pm.execute_notebook(str(nbin), str(nbout), parameters)
  File "/Users/sukrit/miniconda3/envs/experiments-binding-affinity/lib/python3.8/site-packages/papermill/execute.py", line 118, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/Users/sukrit/miniconda3/envs/experiments-binding-affinity/lib/python3.8/site-packages/papermill/execute.py", line 230, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [7]":
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-56f51f7ca191> in <module>
----> 1 dataset = import_object(DATASET_CLS).from_source(**DATASET_KWARGS)
      2 dataset

~/miniconda3/envs/experiments-binding-affinity/lib/python3.8/site-packages/kinoml/datasets/chembl.py in from_source(cls, filename, measurement_types, sample, **kwargs)
     66                     zf.extractall(tmpdir)
     67                 cached_path.parent.mkdir(parents=True, exist_ok=True)
---> 68                 shutil.copyfile(Path(tmpdir) / csv_filename, cached_path)
     69 
     70         df = pd.read_csv(cached_path)

~/miniconda3/envs/experiments-binding-affinity/lib/python3.8/shutil.py in copyfile(src, dst, follow_symlinks)
    262         os.symlink(os.readlink(src), dst)
    263     else:
--> 264         with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    265             # macOS
    266             if _HAS_FCOPYFILE:

FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/3q/r0xmt3qn6xq02b3p08xbr54r0000gn/T/tmpcilygxcr/activities-chembl27_v0.2.csv'
```

Error stack trace for **linux**:
```
(experiments-binding-affinity) 12 singhs15@lt22:~/kinoml-workshop/openkinome/experiments-binding-affinity$ python run_notebook.py features/featurize-template.ipynb features/example-ligand-only-chembl28-morgan512-1k-subsample.py 
Executing:  28%|███████████████████▊                                                    | 8/29 [00:05<00:14,  1.48cell/s]
Traceback (most recent call last):
  File "run_notebook.py", line 51, in <module>
    main()
  File "run_notebook.py", line 47, in main
    pm.execute_notebook(str(nbin), str(nbout), parameters)
  File "/home/singhs15/miniconda3/envs/experiments-binding-affinity/lib/python3.8/site-packages/papermill/execute.py", line 118, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/singhs15/miniconda3/envs/experiments-binding-affinity/lib/python3.8/site-packages/papermill/execute.py", line 230, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-baec478d6de7> in <module>
     19 OUT.mkdir(parents=True, exist_ok=True)
     20 
---> 21 print(f"This notebook:           HERE = ~/{HERE.relative_to(Path.home())}")
     22 print(f"This repo:               REPO = ~/{REPO.relative_to(Path.home())}")
     23 print(f"Outputs in:               OUT = ~/{OUT.relative_to(Path.home())}")

~/miniconda3/envs/experiments-binding-affinity/lib/python3.8/pathlib.py in relative_to(self, *other)
    905         if (root or drv) if n == 0 else cf(abs_parts[:n]) != cf(to_abs_parts):
    906             formatted = self._format_parsed_parts(to_drv, to_root, to_parts)
--> 907             raise ValueError("{!r} does not start with {!r}"
    908                              .format(str(self), str(formatted)))
    909         return self._from_parsed_parts('', root if n == 1 else '',

ValueError: '/lila/home/singhs15/kinoml-workshop/openkinome/experiments-binding-affinity/features/example-ligand-only-chembl28-morgan512-1k-subsample' does not start with '/home/singhs15'
```

**Comment by jaimergp** [comment]
The `linux` issue should be fixed by the last merge. Please `git pull` your `experiments-*` repo and re-run the examples! 🤞

**Comment by jaimergp** [comment]
For the `macos` issue, I think the environment has not been updated with the latest `kinoml`. Go to the (git pull-ed) `kinoml` _repo_, activate the the `experiments-binding-affinity` _environment_, run `pip install -U .`. Then, rerun the examples 🤞
